### ISSUE TITLE
in volos-swagger the spec of the token endpoint expects the scope param to be in the query but the volos-oauth-common connect middleware ignores it

### ISSUE THREAD

**Issue by borisirota** [apigee-127/volos#47]
Hi,

As you can see here:
https://github.com/apigee-127/volos/blob/master/swagger/spec/oauth_operations.yaml#L96
the scope param expected to be in the query.

In addition, the volos-swagger module adds dynamically the token endpoints paths defined in the swagger document:

``` yaml
x-a127-services:
  oauth2:
    provider: volos-oauth-redis
    ...
    tokenPaths:  # These will be added to your paths section for you
        token: /accesstoken
        invalidate: /invalidate
```

and adds a middleware to take care of that:
https://github.com/apigee-127/volos/blob/master/swagger/lib/controllers/volos-oauth.js#L39

Now, the middleware defined in the volos-oauth-common module:
https://github.com/apigee-127/volos/blob/master/oauth/common/lib/oauth-connect.js#L63
and as you can see there is no reference to the scope param which in the query. As a workaround I'm passing it in the body but it should be as expected in the spec (defined in volos-swagger) and should be extracted from the query and added to the body here:
https://github.com/apigee-127/volos/blob/master/oauth/common/lib/oauth-connect.js#L68

Thanks,
Boris
